### ISSUE TITLE
How to slove the datalaoder problem when training the model?

### ISSUE THREAD

**Issue by Sranc3** [jxbbb/ADAPT#7]
When I try to use the officile code to train the mdoel, I got the problem when laoding the training data:

Original Traceback (most recent call last):
  File "/home/mayue/miniconda3/envs/ADAPT/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/mayue/miniconda3/envs/ADAPT/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mayue/miniconda3/envs/ADAPT/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/csr/ADAPT/src/datasets/vision_language_tsv.py", line 395, in __getitem__
    raw_frames, is_video = self.get_visual_data(img_idx, start, end)
  File "/home/csr/ADAPT/src/datasets/vision_language_tsv.py", line 322, in get_visual_data
    row = self.get_row_from_tsv(self.visual_tsv, idx)
  File "/home/csr/ADAPT/src/datasets/vision_language_tsv.py", line 171, in get_row_from_tsv
    assert row[0].split('/')[0] == self.image_keys[img_idx].split('_')[-1] or row[0].split('_')[-1] == self.image_keys[img_idx].split('_')[-1]
AssertionError

I have seen the original code and I guess you have faced with the same problem, could you tell me how to fix it, thank you very much!

**Comment by jxbbb** [comment]
Thanks for your interests. I have trained the model again but do not find the bugs. I print some examples in this lane and hope this can help you.
<img width="927" alt="image" src="https://github.com/jxbbb/ADAPT/assets/61310817/7c1148d9-9529-4675-8615-74b2d21b46ec">
<img width="971" alt="image" src="https://github.com/jxbbb/ADAPT/assets/61310817/ad4c7612-2d2f-4b74-9002-16f68ae00e93">

**Comment by Sranc3** [comment]
Thanks for your reply, It may be something wrong with my local train_info files, we will check it carefuly. Thanks again!

**Comment by Sranc3** [comment]
> Thanks for your reply, It may be something wrong with my local train_info files, we will check it carefuly. Thanks again!

I have finally figured out that it's the problem with the download file 'training_32frames_img_size256.img.tsv', it works well in test dataloader and val datalaoder, but the some of the contents are missing in training tsv, and I get a blank **row**.
![image](https://github.com/jxbbb/ADAPT/assets/82691640/73e20540-53a6-4087-9289-7c6e5f21a5bc)

**Comment by jxbbb** [comment]
It seems that some files in `dataset` or `dataset_part` are missed. You can check the data structure in https://github.com/jxbbb/ADAPT#dataset-preparation. Note that `dataset` and `dataset_part` are both needed when training.

**Comment by Sranc3** [comment]
Sorry to bother you again, we have redownloaded the code and data, but sitll we get the following problem:
![image](https://github.com/jxbbb/ADAPT/assets/82691640/07dac926-a49c-48e0-b8a3-eba70c711c8d)
It seems that the gt_signals(torch.size(715)) and pred_signals(torch.size(715,1)) have the wrong shape, so what are they supposed to be?

**Comment by jxbbb** [comment]
Maybe you can pull the latest code in the hub to your local directory. If this doesn't work, please let me know and I will clone the codes myself and go through the whole process again.

**Comment by Sranc3** [comment]
Yes, we are using the latest code, and we don't make any changes.
